import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL is required");
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });

const concepts = [
  { slug: "nukleotyd", name: "nukleotyd", objective: "mol_nucleotide_structure", aliases: ["nukleotyd", "nukleotydy"], short: "Podstawowa jednostka budująca kwasy nukleinowe: DNA i RNA.", explanation: "Każdy nukleotyd ma trzy części: cukier pięciowęglowy, resztę fosforanową(V) i zasadę azotową. Cukier z fosforanem tworzą powtarzalny szkielet nici, a kolejność zasad niesie informację genetyczną. W DNA cukrem jest deoksyryboza, a w RNA ryboza.", why: "Łączenie nukleotydów pozwala utworzyć nić kwasu nukleinowego. Zrozumienie jego budowy wyjaśnia później komplementarność, kierunkowość nici i replikację DNA.", misconception: "Nukleotyd nie jest całą nicią DNA ani samą zasadą azotową. Zasada jest tylko jedną z jego trzech części.", example: "Wyobraź sobie koralik z trzema elementami: zaczepem (fosforan), korpusem (cukier) i kolorową etykietą (zasada). Zaczepy i korpusy tworzą łańcuch, a kolejność etykiet przechowuje informację.", check: "Wymień trzy części nukleotydu i wskaż, które z nich tworzą powtarzalny szkielet nici.", transfer: "Uczeń zaznaczył na schemacie samą adeninę i nazwał ją nukleotydem. Wyjaśnij, czego brakuje, aby zaznaczony element był całym nukleotydem." },
  { slug: "deoksyryboza", name: "deoksyryboza", objective: "mol_nucleotide_structure", aliases: ["deoksyryboza", "deoksyrybozy"], short: "Pięciowęglowy cukier obecny w nukleotydach DNA.", explanation: "Deoksyryboza łączy zasadę azotową z resztą fosforanową i jest częścią szkieletu cukrowo-fosforanowego. Numery atomów węgla cukru pozwalają określić końce 3′ i 5′ nici.", why: "Jej budowa nadaje nici DNA kierunkowość i wyznacza miejsce dołączania kolejnego nukleotydu.", misconception: "Deoksyryboza nie jest zasadą azotową ani całym nukleotydem.", example: "Na uproszczonym schemacie nukleotydu cukier jest elementem centralnym: z jednej strony łączy się z zasadą, a z drugiej z fosforanem.", check: "Z czym łączy się deoksyryboza w pojedynczym nukleotydzie?", transfer: "Dlaczego bez numeracji atomów węgla deoksyrybozy trudno byłoby opisać kierunek nici DNA?" },
  { slug: "reszta-fosforanowa", name: "reszta fosforanowa(V)", objective: "mol_nucleotide_structure", aliases: ["reszta fosforanowa", "reszty fosforanowej", "fosforan"], short: "Jedna z trzech części nukleotydu, uczestnicząca w budowie szkieletu nici.", explanation: "Reszta fosforanowa łączy cukry sąsiednich nukleotydów poprzez wiązania fosfodiestrowe. Wzdłuż nici powtarza się więc układ cukier–fosforan–cukier–fosforan.", why: "Bez tych połączeń pojedyncze nukleotydy nie utworzyłyby trwałego łańcucha.", misconception: "Reszta fosforanowa nie jest samodzielnym nukleotydem i nie łączy komplementarnych zasad dwóch nici.", example: "W naszyjniku odpowiada łącznikowi między kolejnymi koralikami; nie przechowuje litery informacji, ale spaja łańcuch.", check: "Jaką część nici współtworzy reszta fosforanowa i co ze sobą łączy?", transfer: "Co stałoby się ze szkieletem nici, gdyby nie mogły powstawać wiązania z udziałem reszt fosforanowych?" },
  { slug: "zasada-azotowa", name: "zasada azotowa", objective: "mol_nucleotide_structure", aliases: ["zasada azotowa", "zasady azotowej", "zasady azotowe"], short: "Zmienna część nukleotydu współtworząca zapis informacji genetycznej.", explanation: "W DNA występują adenina, tymina, cytozyna i guanina. W RNA zamiast tyminy występuje uracyl. To kolejność zasad, a nie cukrów lub fosforanów, różnicuje zapis informacji.", why: "Swoiste parowanie zasad umożliwia odtworzenie nici komplementarnej podczas kopiowania DNA.", misconception: "Sama zasada azotowa nie jest nukleotydem; nukleotyd zawiera także cukier i fosforan.", example: "Jeśli szkielet nici porównać do taśmy, zasady są zapisanymi na niej literami: A, T, C i G.", check: "Która część nukleotydu zmienia się i współtworzy sekwencję informacji?", transfer: "Dlaczego zamiana jednej zasady może zmienić informację, mimo że szkielet cukrowo-fosforanowy pozostaje taki sam?" },
  { slug: "nic-polinukleotydowa", name: "nić polinukleotydowa", objective: "mol_nucleotide_structure", aliases: ["nić polinukleotydowa", "łańcuch polinukleotydowy", "nici polinukleotydowej"], short: "Uporządkowany łańcuch wielu nukleotydów połączonych wiązaniami fosfodiestrowymi.", explanation: "Na zewnątrz nici powtarzają się cukry i fosforany, tworząc szkielet. Do cukrów są dołączone zasady azotowe, których kolejność stanowi sekwencję. Nić ma chemicznie różne końce 5′ i 3′.", why: "DNA i RNA przechowują informację właśnie w postaci sekwencji nukleotydów ułożonych w nici.", misconception: "Nić polinukleotydowa nie oznacza pary zasad ani całej podwójnej helisy; jest pojedynczym łańcuchem.", example: "Fragment A–C–G opisuje kolejność zasad jednej nici, podczas gdy jej szkielet nadal tworzy powtarzalny układ cukier–fosforan.", check: "Co tworzy szkielet nici, a co stanowi jej zmienną sekwencję?", transfer: "Dwie nici mają taki sam szkielet, lecz inną kolejność zasad. Czy przechowują tę samą informację? Uzasadnij." },
  { slug: "wiazanie-fosfodiestrowe", name: "wiązanie 3′,5′-fosfodiestrowe", objective: "mol_nucleotide_structure", aliases: ["wiązanie fosfodiestrowe", "wiązanie 3′,5′-fosfodiestrowe", "wiązania fosfodiestrowe"], short: "Wiązanie kowalencyjne łączące kolejne nukleotydy w jednej nici.", explanation: "Powstaje między resztą fosforanową a cukrami sąsiednich nukleotydów, łącząc pozycję 3′ jednego cukru z pozycją 5′ następnego. Wiele takich wiązań tworzy szkielet cukrowo-fosforanowy.", why: "Zapewnia trwałość pojedynczej nici i nadaje jej określoną kierunkowość.", misconception: "Nie jest wiązaniem wodorowym i nie łączy zasad należących do dwóch przeciwnych nici.", example: "Na schemacie jednej nici szukaj połączenia biegnącego naprzemiennie przez cukier i fosforan, a nie linii między parami A–T lub C–G.", check: "Co dokładnie łączy wiązanie fosfodiestrowe i w której części DNA go szukać?", transfer: "Uczeń wskazał linię między A i T jako wiązanie fosfodiestrowe. Wyjaśnij jego błąd." },
  { slug: "kierunkowosc-nici", name: "kierunkowość nici 5′→3′", objective: "mol_nucleotide_structure", aliases: ["kierunkowość nici", "kierunek 5′→3′", "koniec 5′", "koniec 3′", "końcu 5′", "końcu 3′", "grupa 3′-OH"], short: "Właściwość nici wynikająca z jej dwóch chemicznie różnych końców: 5′ i 3′.", explanation: "Oznaczenia pochodzą od numerów atomów węgla cukru. Na końcu 5′ znajduje się grupa związana z węglem 5′, a na końcu 3′ wolna grupa 3′-OH. Sekwencje standardowo zapisuje się od 5′ do 3′, a nowa nić jest wydłużana przez dołączanie nukleotydów do końca 3′.", why: "Bez kierunkowości nie da się poprawnie zapisać nici komplementarnej ani wyjaśnić działania enzymów podczas replikacji.", misconception: "3′ i 5′ nie są osobnymi rodzajami nici, numerami nukleotydów ani stałą lewą i prawą stroną rysunku.", example: "Jeśli jedną nić zapisano 5′-A C G-3′, jej koniec z A jest tu umownie po lewej tylko dlatego, że zapisano ją w standardowym kierunku; po obróceniu rysunku chemiczne końce się nie zmienią.", check: "Co oznaczają symbole 5′ i 3′ i do którego końca dołączany jest kolejny nukleotyd?", transfer: "Nić narysowano pionowo. Jak rozpoznasz jej kierunek, skoro 5′ nie oznacza lewej strony?" },
  { slug: "komplementarnosc", name: "komplementarność zasad", objective: "mol_dna_structure_complementarity", aliases: ["komplementarność", "komplementarne", "nić komplementarna", "zasada komplementarności"], short: "Reguła swoistego parowania zasad azotowych w DNA.", explanation: "Adenina tworzy parę z tyminą, a cytozyna z guaniną. Dzięki temu sekwencja jednej nici jednoznacznie wyznacza sekwencję drugiej, z uwzględnieniem ich przeciwnej kierunkowości.", why: "Jest podstawą wiernego kopiowania DNA i odtwarzania brakującej nici.", misconception: "Nić komplementarna nie jest identycznym powtórzeniem liter nici wyjściowej.", example: "Do fragmentu 5′-A C G-3′ pasują zasady T G C, zapisane na drugiej nici antyrównolegle: 3′-T G C-5′.", check: "Jakie pary zasad występują w DNA?", transfer: "Zapisz komplementarną, antyrównoległą nić do sekwencji 5′-A A C G-3′." },
  { slug: "antyrownoleglosc", name: "antyrównoległość nici", objective: "mol_dna_structure_complementarity", aliases: ["antyrównoległość", "antyrównoległe", "nici antyrównoległe"], short: "Ułożenie dwóch nici DNA biegnących w przeciwnych kierunkach.", explanation: "Gdy jedna nić jest skierowana od końca 5′ do 3′, sąsiednia biegnie od 3′ do 5′. Dotyczy to orientacji szkieletów obu nici, a nie kierunku czytania kartki.", why: "Warunkuje prawidłowe parowanie zasad i sposób kopiowania obu nici podczas replikacji.", misconception: "Antyrównoległość nie oznacza przypadkowo różnych sekwencji ani położenia jednej nici do góry nogami bez znaczenia chemicznego.", example: "Zapis 5′-A C G-3′ nad 3′-T G C-5′ pokazuje jednocześnie komplementarność i przeciwną orientację.", check: "Jeśli pierwsza nić biegnie 5′→3′, w jakim kierunku biegnie ustawiona obok niej druga?", transfer: "Uczeń zapisał obie nici podwójnego DNA od 5′ do 3′ po tej samej stronie. Co powinien poprawić?" },
  { slug: "podwojna-helisa", name: "podwójna helisa", objective: "mol_dna_structure_complementarity", aliases: ["podwójna helisa", "podwójnej helisy"], short: "Przestrzenna postać DNA zbudowana z dwóch skręconych, antyrównoległych nici.", explanation: "Szkielety cukrowo-fosforanowe znajdują się na zewnątrz, a komplementarne zasady są skierowane do środka i łączą obie nici wiązaniami wodorowymi.", why: "Taka organizacja chroni informację, stabilizuje DNA i pozwala rozdzielić nici podczas kopiowania.", misconception: "Podwójna helisa nie jest jedną skręconą nicią ani łańcuchem połączonym wiązaniami wodorowymi wzdłuż szkieletu.", example: "Model drabiny: poręcze odpowiadają szkieletom cukrowo-fosforanowym, szczeble parom zasad, a cała drabina jest skręcona.", check: "Co znajduje się na zewnątrz helisy, a co tworzy jej wewnętrzne pary?", transfer: "Który element modelu drabiny musiałby się rozłączyć, aby dwie nici mogły posłużyć jako matryce?" },
  { slug: "wiazanie-wodorowe", name: "wiązanie wodorowe", objective: "mol_dna_structure_complementarity", aliases: ["wiązanie wodorowe", "wiązania wodorowe", "wiązaniami wodorowymi"], short: "Oddziaływanie łączące komplementarne zasady należące do dwóch nici DNA.", explanation: "Pojedyncze wiązanie wodorowe jest słabsze od kowalencyjnego, lecz bardzo wiele takich oddziaływań stabilizuje helisę. Mogą zostać rozerwane bez przerywania szkieletu nici.", why: "DNA jest jednocześnie stabilne i możliwe do czasowego rozdzielenia podczas replikacji lub odczytu informacji.", misconception: "Wiązania wodorowe nie łączą kolejnych nukleotydów wzdłuż jednej nici; robią to wiązania fosfodiestrowe.", example: "Rozdzielanie nici przypomina rozpinanie zamka: puszczają połączenia między parami zasad, ale obie taśmy pozostają całe.", check: "Gdzie w DNA występują wiązania wodorowe, a gdzie fosfodiestrowe?", transfer: "Dlaczego rozdzielenie nici DNA nie musi oznaczać pocięcia każdej nici na pojedyncze nukleotydy?" },
  { slug: "replikacja-semikonserwatywna", name: "replikacja semikonserwatywna", objective: "mol_replication_mechanism", aliases: ["replikacja semikonserwatywna", "semikonserwatywna", "półzachowawcza"], short: "Sposób kopiowania DNA, w którym każda cząsteczka potomna zawiera jedną nić rodzicielską i jedną nową.", explanation: "Najpierw dwie nici DNA rozdzielają się. Każda stara nić służy jako matryca, do której dobierane są komplementarne nukleotydy, dlatego powstają dwie dwuniciowe cząsteczki.", why: "Mechanizm łączy budowę DNA i komplementarność z wiernym przekazywaniem informacji przed podziałem komórki.", misconception: "Semikonserwatywna nie znaczy, że kopiowana jest tylko połowa DNA; każda cząsteczka potomna zawiera pełną informację.", example: "Oznacz stare nici kolorem granatowym, a nowe zielonym. Po replikacji każda z dwóch cząsteczek ma jedną nić granatową i jedną zieloną.", check: "Z jakich nici składa się każda cząsteczka DNA po replikacji semikonserwatywnej?", transfer: "Po jednym cyklu replikacji w środowisku ze znakowanymi nowymi nukleotydami, które nici będą znakowane: stare, nowe czy wszystkie? Uzasadnij." },
] as const;

const retiredConceptSlugs = ["koniec-3", "koniec-5"];

function normalize(value: string) {
  return value.toLocaleLowerCase("pl-PL").normalize("NFKC").replace(/\s+/gu, " ").trim();
}

async function main() {
  const curriculum = await db.curriculumVersion.findUniqueOrThrow({ where: { code: "PL-BIO-LO-2024" } });
  for (const item of concepts) {
    const objective = await db.learningObjective.findUniqueOrThrow({ where: { code: item.objective } });
    const concept = await db.concept.upsert({
      where: { curriculumVersionId_slug: { curriculumVersionId: curriculum.id, slug: item.slug } },
      update: { name: item.name, shortDefinition: item.short, simpleExplanation: item.explanation, whyItMatters: item.why, commonMisconception: item.misconception, concreteExample: item.example, checkQuestion: item.check, transferQuestion: item.transfer, active: true, origin: "CURATED", reviewStatus: "APPROVED", createdForStudentId: null, sourceQuestion: null },
      create: { curriculumVersionId: curriculum.id, slug: item.slug, name: item.name, shortDefinition: item.short, simpleExplanation: item.explanation, whyItMatters: item.why, commonMisconception: item.misconception, concreteExample: item.example, checkQuestion: item.check, transferQuestion: item.transfer },
    });
    await db.conceptObjective.upsert({
      where: { conceptId_learningObjectiveId: { conceptId: concept.id, learningObjectiveId: objective.id } },
      update: {},
      create: { conceptId: concept.id, learningObjectiveId: objective.id },
    });
    for (const alias of new Set([item.name, ...item.aliases])) {
      await db.conceptAlias.upsert({
        where: { conceptId_normalizedAlias: { conceptId: concept.id, normalizedAlias: normalize(alias) } },
        update: { alias },
        create: { conceptId: concept.id, alias, normalizedAlias: normalize(alias) },
      });
    }
  }
  await db.concept.updateMany({
    where: { curriculumVersionId: curriculum.id, slug: { in: retiredConceptSlugs } },
    data: { active: false },
  });
  console.log(`Seeded ${concepts.length} controlled concepts`);
}

main().finally(() => db.$disconnect());
