export const quickTestUnit = {
  slug: "genetyka-klasyczna-test",
  title: "Genetyka klasyczna — szybki dział testowy",
  order: 2,
  description: "Krótki zakres z początku rozdziału 2 podręcznika: podstawowe pojęcia genetyczne, I prawo Mendla i proste krzyżówki jednogenowe.",
  topic: { title: "2.1. Dziedziczenie cech. I prawo Mendla", order: 1 },
  objectives: [
    {
      code: "classic_genotype_phenotype_test",
      order: 1,
      title: "Genotyp, fenotyp, homozygota i heterozygota",
      description: "Rozróżnia gen i allel, genotyp i fenotyp oraz homozygotę i heterozygotę; przewiduje ujawnienie cechy przy dominacji zupełnej.",
      diagnosticPrompt: "Osobnik ma genotyp Aa, a allel A jest dominujący nad a. Czy jest homozygotą czy heterozygotą i który fenotyp się ujawni? Wyjaśnij krótko.",
      hook: "Dwie rośliny mogą wyglądać tak samo, chociaż jedna ma allele AA, a druga Aa. Wygląd nie zawsze ujawnia cały genotyp.",
      microExplanation: "Gen to fragment DNA związany z określoną informacją, a allele to różne wersje tego samego genu. Genotyp opisuje posiadany zestaw alleli, np. AA, Aa lub aa, natomiast fenotyp to obserwowalna cecha. Dwa jednakowe allele oznaczają homozygotę, a dwa różne — heterozygotę. Przy dominacji zupełnej AA i Aa mają fenotyp dominujący, a fenotyp recesywny ujawnia się tylko u aa.",
      workedExample: "Jeśli A warunkuje kolczaste owoce, a a — gładkie, roślina Aa jest heterozygotą i ma owoce kolczaste. Sama kolczasta powierzchnia nie pozwala jednak rozstrzygnąć, czy genotyp to AA, czy Aa.",
      practicePrompt: "Dla genotypów AA, Aa i aa wskaż: homozygota czy heterozygota oraz fenotyp dominujący czy recesywny.",
      transferPrompt: "Dwie rośliny mają ten sam fenotyp dominujący. Jedna ma genotyp AA, druga Aa. Wyjaśnij, dlaczego wyglądają tak samo i czego nie można ustalić na podstawie samego fenotypu.",
      visualData: {
        type: "sequence",
        caption: "Od genu do obserwowanej cechy",
        steps: [
          { label: "Gen", detail: "fragment DNA związany z informacją o cesze" },
          { label: "Allele", detail: "różne wersje tego samego genu, np. A i a" },
          { label: "Genotyp", detail: "zestaw alleli: AA, Aa albo aa" },
          { label: "Fenotyp", detail: "cecha, która ujawnia się u organizmu" },
        ],
      },
      importance: 1,
      maturaRelevant: true,
    },
    {
      code: "classic_mendel_punnett_test",
      order: 2,
      title: "I prawo Mendla i krzyżówka jednogenowa",
      description: "Wyjaśnia rozdzielenie alleli do gamet i wykorzystuje szachownicę Punnetta do przewidywania genotypów oraz fenotypów potomstwa.",
      diagnosticPrompt: "Jakie dwa rodzaje gamet wytwarza heterozygota Aa i dlaczego każda gameta zawiera tylko jeden z tych alleli?",
      hook: "Dwoje rodziców z fenotypem dominującym może mieć potomka z cechą recesywną. Szachownica Punnetta pokazuje, kiedy jest to możliwe.",
      microExplanation: "Zgodnie z I prawem Mendla podczas powstawania gamet dwa allele danego genu rozdzielają się, dlatego każda gameta otrzymuje tylko jeden allel. Heterozygota Aa tworzy więc gamety A i a. W szachownicy Punnetta zapisuje się gamety obojga rodziców, łączy je we wszystkich możliwych parach, a następnie liczy genotypy i wynikające z nich fenotypy potomstwa.",
      workedExample: "W krzyżówce Aa × Aa każdy rodzic tworzy gamety A i a. Cztery równoprawdopodobne połączenia to AA, Aa, Aa i aa. Daje to 25% AA, 50% Aa i 25% aa; przy dominacji zupełnej stosunek fenotypu dominującego do recesywnego wynosi 3:1.",
      practicePrompt: "Wykonaj krzyżówkę Aa × aa: wypisz gamety rodziców oraz prawdopodobieństwa genotypów i fenotypów potomstwa.",
      transferPrompt: "Allel D warunkujący Rh+ jest dominujący. Dwoje rodziców Rh+ ma dziecko Rh−. Ustal genotypy rodziców i prawdopodobieństwo, że ich kolejne dziecko również będzie Rh−. Uzasadnij szachownicą Punnetta.",
      visualData: {
        type: "sequence",
        caption: "Jak rozwiązać prostą krzyżówkę genetyczną",
        steps: [
          { label: "Genotypy rodziców", detail: "zapisz pary alleli obojga osobników" },
          { label: "Gamety", detail: "do każdej trafia jeden allel danego genu" },
          { label: "Połączenia", detail: "wypełnij pola szachownicy Punnetta" },
          { label: "Wynik", detail: "policz genotypy, a potem odpowiadające im fenotypy" },
        ],
      },
      importance: 1,
      maturaRelevant: true,
    },
  ],
  source: {
    title: "Biologia na czasie 4 — rozdział 2, szybki zakres testowy",
    provenance: "User-provided scan; biologia-na-czasie-4.pdf; chapter 2 pages 66-74; curated from local OCR",
    rightsNote: "Prywatne użycie legalnie posiadanego egzemplarza; w bazie zapisano kontrolowane opracowanie, bez publicznego udostępniania skanu.",
    version: "wydanie 2022; kontrolowane opracowanie lokalnego OCR",
    chunks: [
      {
        locator: "book-pages:66-67",
        content: "Gen jest fragmentem DNA zawierającym informację potrzebną do wytworzenia białka lub RNA, a allele są różnymi wersjami genu. Homozygota ma dwa takie same allele (AA albo aa), heterozygota dwa różne (Aa). Genotyp opisuje zestaw genów lub — w zadaniu jednogenowym — układ alleli, natomiast fenotyp obejmuje ujawnione cechy. Przy dominacji zupełnej jeden allel dominujący wystarcza do ujawnienia cechy dominującej, a cecha recesywna ujawnia się przy dwóch allelach recesywnych.",
        metadata: { bookPageFrom: 66, bookPageTo: 67, topicOrder: 1, section: "lesson", extraction: "curated_local_ocr" },
      },
      {
        locator: "book-pages:69-72",
        content: "I prawo Mendla, nazywane prawem czystości gamet, mówi, że do gamety przechodzi tylko jeden allel z danej pary. Heterozygota Aa tworzy gamety A i a. W krzyżówce Aa × Aa możliwe genotypy potomstwa występują w proporcji 1 AA : 2 Aa : 1 aa, a przy dominacji zupełnej fenotypy dominujący i recesywny w proporcji 3:1. Szachownica Punnetta zestawia rodzaje gamet rodziców i wszystkie możliwe połączenia alleli potomstwa.",
        metadata: { bookPageFrom: 69, bookPageTo: 72, topicOrder: 1, section: "worked_tasks", extraction: "curated_local_ocr" },
      },
      {
        locator: "book-page:74",
        content: "Jeżeli allel D warunkujący Rh+ jest dominujący, osoba Rh− ma genotyp dd. Dwoje rodziców Rh+ może mieć dziecko Rh− tylko wtedy, gdy oboje są heterozygotami Dd. Krzyżówka Dd × Dd daje jedno pole dd na cztery, czyli prawdopodobieństwo 25% dla fenotypu Rh−.",
        metadata: { bookPage: 74, topicOrder: 1, section: "worked_tasks", extraction: "curated_local_ocr" },
      },
    ],
  },
} as const;
